INSERT IGNORE INTO knowledge_area (id, description) VALUES
    (1, 'Ciências Humanas'),
    (2, 'Ciências da Natureza'),
    (3, 'Linguagens e Códigos'),
    (4, 'Matemática');

INSERT IGNORE INTO subject (id, description, knowledge_area_id) VALUES
    (1, 'História', 1),
    (2, 'Geografia', 1),
    (3, 'Filosofia', 1),
    (4, 'Sociologia', 1),
    (5, 'Biologia', 2),
    (6, 'Física', 2),
    (7, 'Química', 2),
    (8, 'Língua Portuguesa', 3),
    (9, 'Literatura', 3),
    (10, 'Língua Inglesa', 3),
    (11, 'Língua Espanhola', 3),
    (12, 'Artes', 3),
    (13, 'Educação Física', 3),
    (14, 'Matemática', 4);

INSERT IGNORE INTO topic (id, description, subject_id) VALUES
    (1, 'Brasil Colônia', 1),
    (2, 'Brasil Império', 1),
    (3, 'República Velha', 1),
    (4, 'Era Vargas', 1),
    (5, 'Ditadura Militar', 1),
    (6, 'Idade Média', 1),
    (7, 'Revolução Industrial', 1),
    (8, 'Primeira e Segunda Guerra Mundial', 1),
    (9, 'Guerra Fria', 1),
    (10, 'Cartografia', 2),
    (11, 'Geologia e Relevo', 2),
    (12, 'Climatologia', 2),
    (13, 'Hidrografia', 2),
    (14, 'Biomas Brasileiros', 2),
    (15, 'Geografia Urbana', 2),
    (16, 'Geografia Agrária', 2),
    (17, 'Demografia', 2),
    (18, 'Globalização e Geopolítica', 2),
    (19, 'Filosofia Antiga', 3),
    (20, 'Filosofia Medieval', 3),
    (21, 'Filosofia Moderna', 3),
    (22, 'Filosofia Contemporânea', 3),
    (23, 'Ética e Moral', 3),
    (24, 'Filosofia Política', 3),
    (25, 'Teoria do Conhecimento', 3),
    (26, 'Clássicos da Sociologia', 4),
    (27, 'Trabalho e Sociedade', 4),
    (28, 'Cultura e Indústria Cultural', 4),
    (29, 'Movimentos Sociais', 4),
    (30, 'Cidadania e Direitos Humanos', 4),
    (31, 'Estratificação e Desigualdade Social', 4),
    (32, 'Citologia', 5),
    (33, 'Histologia', 5),
    (34, 'Genética', 5),
    (35, 'Evolução', 5),
    (36, 'Ecologia', 5),
    (37, 'Fisiologia Humana', 5),
    (38, 'Botânica', 5),
    (39, 'Zoologia', 5),
    (40, 'Microbiologia e Doenças', 5),
    (41, 'Cinemática', 6),
    (42, 'Dinâmica', 6),
    (43, 'Estática', 6),
    (44, 'Trabalho, Energia e Potência', 6),
    (45, 'Hidrostática', 6),
    (46, 'Termologia e Termodinâmica', 6),
    (47, 'Óptica Geométrica', 6),
    (48, 'Ondulatória', 6),
    (49, 'Eletrostática', 6),
    (50, 'Eletrodinâmica', 6),
    (51, 'Eletromagnetismo', 6),
    (52, 'Física Moderna', 6),
    (53, 'Estrutura Atômica', 7),
    (54, 'Tabela Periódica', 7),
    (55, 'Ligações Químicas', 7),
    (56, 'Funções Inorgânicas', 7),
    (57, 'Reações Químicas', 7),
    (58, 'Estequiometria', 7),
    (59, 'Soluções', 7),
    (60, 'Termoquímica', 7),
    (61, 'Cinética Química', 7),
    (62, 'Equilíbrio Químico', 7),
    (63, 'Eletroquímica', 7),
    (64, 'Química Orgânica', 7),
    (65, 'Fonética e Fonologia', 8),
    (66, 'Morfologia e Classes Gramaticais', 8),
    (67, 'Sintaxe', 8),
    (68, 'Concordância Verbal e Nominal', 8),
    (69, 'Regência e Crase', 8),
    (70, 'Pontuação', 8),
    (71, 'Semântica e Figuras de Linguagem', 8),
    (72, 'Interpretação de Texto', 8),
    (73, 'Variação Linguística', 8),
    (74, 'Gêneros Textuais', 8),
    (75, 'Quinhentismo e Barroco', 9),
    (76, 'Arcadismo', 9),
    (77, 'Romantismo', 9),
    (78, 'Realismo e Naturalismo', 9),
    (79, 'Parnasianismo e Simbolismo', 9),
    (80, 'Pré-Modernismo', 9),
    (81, 'Modernismo no Brasil', 9),
    (82, 'Literatura Contemporânea', 9),
    (83, 'Interpretação de Texto em Inglês', 10),
    (84, 'Vocabulário e Cognatos', 10),
    (85, 'Verb Tenses', 10),
    (86, 'Modal Verbs', 10),
    (87, 'Conectivos e Coesão', 10),
    (88, 'Interpretação de Texto em Espanhol', 11),
    (89, 'Vocabulário e Falsos Cognatos', 11),
    (90, 'Tempos Verbais', 11),
    (91, 'Conectores e Coesão', 11),
    (92, 'Artes Visuais', 12),
    (93, 'Vanguardas Europeias', 12),
    (94, 'Arte Brasileira', 12),
    (95, 'Música e Movimentos Musicais', 12),
    (96, 'Teatro e Dança', 12),
    (97, 'Esportes e Regras', 13),
    (98, 'Corpo e Saúde', 13),
    (99, 'Lutas, Ginástica e Dança', 13),
    (100, 'Esporte e Sociedade', 13),
    (101, 'Conjuntos e Conjuntos Numéricos', 14),
    (102, 'Razão, Proporção e Porcentagem', 14),
    (103, 'Funções', 14),
    (104, 'Progressões', 14),
    (105, 'Matrizes, Determinantes e Sistemas Lineares', 14),
    (106, 'Análise Combinatória', 14),
    (107, 'Probabilidade', 14),
    (108, 'Estatística', 14),
    (109, 'Geometria Plana', 14),
    (110, 'Geometria Espacial', 14),
    (111, 'Geometria Analítica', 14),
    (112, 'Trigonometria', 14),
    (113, 'Matemática Financeira', 14);